* c/Makefile (asan, asan-*): Run testsuite with sanitizers enabled.  * c/gcc.mk: Extend default sanitizers.

diff --git a/c/Makefile b/c/Makefile
--- a/c/Makefile
+++ b/c/Makefile
@@ -156,6 +156,7 @@ EXE_CFLAGS += $(SANITIZERS) $(OPT_CFLAGS) $(MARCH_FLAGS) $(WARN_CFLAGS) \
 
 # List of test target base names
 TEST_NAMES := eaf nondominated hv hvapprox igd epsilon dominatedsets ndsort
+ASAN_TARGETS := $(addprefix asan-,$(TEST_NAMES))
 TEST_TARGETS := $(addprefix test-,$(TEST_NAMES))
 TIME_TARGETS := $(addprefix time-,$(TEST_NAMES))
 ALL_NAMES := $(TEST_NAMES)
@@ -242,6 +243,27 @@ clean:
 	@$(RM) $(OBJS) $(HV_OBJS) $(HV_LIB)
 
 TESTSUITE:="../testsuite"
+asan: OPT_CFLAGS ?=-Og -g3
+asan: SANITIZERS ?=$(DEFAULT_SANITIZERS)
+asan:
+	@if ! test -d $(TESTSUITE); then  		    	         \
+	    echo "Error: Testsuite not found in $(TESTSUITE)" && exit 1; \
+	fi
+	$(MAKE) all DEBUG=1 SANITIZERS="$(SANITIZERS)" OPT_CFLAGS="$(OPT_CFLAGS)"
+	$(MAKE) $(ASAN_TARGETS)
+
+$(ASAN_TARGETS): target=$(subst asan-,,$@)
+$(ASAN_TARGETS): OPT_CFLAGS ?=-Og -g3
+$(ASAN_TARGETS): SANITIZERS ?=$(DEFAULT_SANITIZERS)
+$(ASAN_TARGETS):
+	$(MAKE) $(target) DEBUG=1 SANITIZERS="$(SANITIZERS)" OPT_CFLAGS="$(OPT_CFLAGS)"
+	$(call ECHO,---> Testing $(target) for errors (DEBUG=1, $(SANITIZERS)) <--- )
+
+	@cd $(TESTSUITE)/$(target) && \
+	export ASAN_OPTIONS='detect_leaks=0:strict_string_checks=1:check_initialization_order=1:detect_invalid_pointer_pairs=2:abort_on_error=1' && \
+	export UBSAN_OPTIONS='print_stacktrace=1:halt_on_error=1' && \
+	../regtest.py $(BINDIR)/$(target)$(EXE) && cd $(PWD)
+
 test: OPT_CFLAGS ?=-Og -g3
 test: SANITIZERS ?=
 test:
